### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by morningxtar** [morningxtar/PDL_2021_groupe_9#2]
Où en êtes vous avec les tests ?

**Comment by morningxtar** [comment]
@machadi Tu peux transformer module en classe pour les tests comme tu avais fait au début
après on va vérifier ensemble

**Comment by machadi** [comment]
@morningxtar c'est fait pour la transformation du module en classe

**Comment by machadi** [comment]
@SANOGOi  test à faire :
test_get_tables_contents_from_url
test_write_csv_files
