### ISSUE TITLE
error in class  __init__.py

### ISSUE THREAD

**Issue by machadi** [morningxtar/PDL_2021_groupe_9#3]
urls = md.transform_wikiurls_to_realurls(f.readlines())
AttributeError: module 'modules.ConverterToCsv' has no attribute 'transform_wikiurls_to_realurls'

**Comment by morningxtar** [comment]
Il ne s'agit pas de venir copier coller les erreurs
Essayer de comprendre et de résoudre les problèmes

**Comment by machadi** [comment]
OK !
