### ISSUE TITLE
Explication 

### ISSUE THREAD

**Issue by morningxtar** [morningxtar/PDL_2021_groupe_9#6]
Anwar il ne suffit pas de commit pour commit
Il faut que ce que tu push ait un sens, J'ai l'impression que tu pousse juste pour que le prof voit que tu contribue
ça ne sert à rien si derrière celà génère des bugs
Aussi j'ai vu ce que t'as mis dans Python_VS_Java.py, je crois avoir déjà dire de ne pas utiliser de chemin absolu
Maintenant ma question est de savoir si ce script fonctionne, est-ce qu'il lance les extracteurs ???

**Comment by machadi** [comment]
GARDE TON IMPRESSION POUR TOI !
Il faillait bien voir ce que j'avais déposé avant de dire n'importe quoi  !!!
Est ce que ta lu le fichier README.md  pour savoir comment exécuter le script  Python_VS_Java.py !!!

**Comment by morningxtar** [comment]
mdr tu penses pouvoir t'en sortir à ce jeu qu'en tu affirmes que je dis n'importe quoi

**Comment by morningxtar** [comment]
mdr tu penses pouvoir t'en sortir à ça quand tu affirmes que je dis n'importe quoi

**Comment by FAMILIAR-project** [comment]
Bonjour, 

Une issue Github n'est pas là pour incriminer un membre d'un projet ou un contributeur. 
Il s'agit de discuter précisément et calmement d'un problème, qu'il soit lié au code, à la documentation, au déploiement, etc. 
L'objectif de PDL est de collaborer: inutile d'être malveillant. Dans n'importe quel projet open source ou en entreprise, ce n'est pas ainsi qu'on collabore. 

Sur l'aspect technique, je préconise trois choses ici:
 * ne pas commiter de .jar dans le repository git... le commit augmente inutilement la taille du repo., et git va de fait devoir gérer l'historique du fichier. Sans compter les problèmes liées à la re-génération du jar qui va poser des conflits
 * le README.md contient des explications (c'est bien!) sur comment construire le .jar. Il faudrait faire en sorte que la création du .jar soit automatique, sans nécessiter des interactions manuelles avec IntelliJ. Utiliser tout simplement maven dans ce cadre là.
 * le script `Python_VS_Java.py` peut faire appel à `mvn` et ensuite dérouler l'exécution des différents extracteurs. 

Merci de réouvrir cette "issue" et de discuter de nouveau du problème et de possibles axes d'améliorations.

**Comment by machadi** [comment]
Done !
