### ISSUE TITLE
jar file

### ISSUE THREAD

**Issue by morningxtar** [morningxtar/PDL_2021_groupe_9#7]
Tu peux mettre ton jar dans le répertoire source et le pousser

**Comment by machadi** [comment]
Done !

**Comment by FAMILIAR-project** [comment]
surtout pas, cf #6

**Comment by morningxtar** [comment]
On doit créer le jar avec mvn, c'est à dire utiliser os.command comme anwar l'a fait dans le Python_VS_Java.py pour construire le jar
Je crois que c'est mvn install
Explication ici : https://www.journaldunet.fr/web-tech/developpement/1203063-comment-creer-un-jar-executable-avec-ses-dependances/
Exemple avec résolution d'une erreur spécifique ici : https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven

**Comment by machadi** [comment]
Done !
